version: '3.8'

services:
  kafka-controller:
    image: apache/kafka:3.7.0
    container_name: kafka-controller 
    environment:
      KAFKA_NODE_ID: 1 
      KAFKA_PROCESS_ROLES: controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-controller:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER 
      KAFKA_LISTENERS: CONTROLLER://0.0.0.0:9093 
      CLUSTER_ID: "5L6g3nShT-eMctk--x86sw"

    ports:
      - "9093:9093"
    networks:
      - app-network 
  kafka-1:
    image: apache/kafka:3.7.0
    container_name: kafka-1 
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092 
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://127.0.0.1:29092

      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-controller:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER 


      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT 

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      KAFKA_LOG_CLEANUP_POLICY: compact 
      KAFKA_LOG_SEGMENT_BYTES: 104857600 
      KAFKA_LOG_RETENTION_BYTES: 1073741824
      KAFKA_LOG_MIN_COMPACTION_LAG_MS: 0
      KAFKA_LOG_RETENTION_MS: 6048000000 
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: "4"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"

      CLUSTER_ID: "5L6g3nShT-eMctk--x86sw"

    ports:
      - "9092:9092"
      - "29092:29092"
      
    networks:
      - app-network
  kafka-2:
    image: apache/kafka:3.7.0
    container_name: kafka-2 
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094,PLAINTEXT_HOST://0.0.0.0:29094 
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9094,PLAINTEXT_HOST://127.0.0.1:29094

      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-controller:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER 


      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT 

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      KAFKA_LOG_CLEANUP_POLICY: compact 
      KAFKA_LOG_SEGMENT_BYTES: 104857600 
      KAFKA_LOG_RETENTION_BYTES: 1073741824
      KAFKA_LOG_MIN_COMPACTION_LAG_MS: 0
      KAFKA_LOG_RETENTION_MS: 6048000000 
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: "4"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"


      CLUSTER_ID: "5L6g3nShT-eMctk--x86sw"

    ports:
      - "9094:9094"
      - "29094:29094"
    networks:
      - app-network

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui 
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka-cluster 
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9092,kafka-2:9094 
    networks:
      - app-network 

  redis:
    container_name: redis 
    image: redis:7.0-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data 
    networks:
      - app-network
    command: redis-server --appendonly yes 

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
    driver: local