apiVersion: v1
kind: ConfigMap 
metadata:
  name: app-config 
  namespace: social-app 
data: 
  MONGODB_URL : "mongodb://admin:password@mongodb-service:27017/socialapp?authSource=admin"

  REDIS_URL: "redis-service:6379"
  REDIS_PASSWORD: "" 

  KAFKA_ADDR: "kafka-1-0.kafka-1-service.social-app.svc.cluster.local:9092,kafka-2-service.social-app.svc.cluster.local:9094"