apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-1
  namespace: social-app
spec:
  serviceName: kafka-1-service
  replicas: 1
  selector:
    matchLabels:
      app: kafka-1
  template:
    metadata:
      labels:
        app: kafka-1
    spec:
      containers:
      - name: kafka-1
        image:  apache/kafka:3.7.0
        ports:
        - containerPort: 9092
          name: plaintext
        env:
          - name: KAFKA_NODE_ID
            value: "2"
          - name: KAFKA_PROCESS_ROLES
            value: "broker"
          - name:  KAFKA_LISTENERS
            value: "PLAINTEXT://0.0.0.0:9092"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://kafka-1-0.kafka-1-service.social-app.svc.cluster.local:9092"
          - name: KAFKA_CONTROLLER_LISTENER_NAMES
            value: "CONTROLLER"
          - name:  KAFKA_CONTROLLER_QUORUM_VOTERS
            value: "1@kafka-controller-0.kafka-controller-service.social-app.svc.cluster.local:9093"
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
          - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
            value: "true"
          - name: KAFKA_LOG_CLEANUP_POLICY
            value: "compact" 
          - name: KAFKA_LOG_SEGMENT_BYTES
            value: "104857600" 
          - name: KAFKA_LOG_RETENTION_BYTES
            value: "1073741824"
          - name: KAFKA_LOG_MIN_COMPACTION_LAG_MS
            value: "0"
          - name: KAFKA_LOG_RETENTION_MS
            value: "6048000000" 
          - name: KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS
            value: "4"
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value:  "1"
          - name:  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
            value:  "1"
          - name:  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
            value: "1"
          - name: CLUSTER_ID
            value: "5L6g3nShT-eMctk--x86sw"

        volumeMounts:
        - name: kafka-1-storage
          mountPath: /var/lib/kafka/data
        resources:
          requests: 
            memory: "512Mi" 
            cpu: "500m" 
          limits: 
            memory: "1Gi" 
            cpu: "1000m" 
        readinessProbe:
          tcpSocket: 
            port : 9092 
          initialDelaySeconds: 30 
          periodSeconds: 10 
          failureThreshold: 3 
        livenessProbe: 
          tcpSocket:
           port: 9092 
          initialDelaySeconds: 60 
          periodSeconds: 20
          failureThreshold: 3 
      volumes:
      - name: kafka-1-storage 
        persistentVolumeClaim: 
          claimName: kafka-1-pvc 

--- 
apiVersion: v1
kind: Service
metadata:
  name: kafka-1-service
  namespace: social-app
spec:
  clusterIP: None
  selector:
    app: kafka-1
  ports:
  - port: 9092
    targetPort: 9092
    name: plaintext 
  publishNotReadyAddresses: true 


