apiVersion: v1
kind: Secret 
metadata:
  name: app-secrets
  namespace: social-app 
type: Opaque 
stringData: 
  JWT_SECRET: "o2gfVvPiOyg2YXGQtecK3MdMI6UZkWQ70XSDBQGFOAk=" 
  REDIS_PASSWORD: ""
  MONGODB_USERNAME: "admin"
  MONGODB_PASSWORD: "password"
  

